#!/usr/bin/env bash
#Transfer files from a client to a server with scp
if [ $# -ne 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

#use scp to transfer the files
scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/

#check the exit status of scp
if [ $? -e1 0 ]; then
	echo "File Transferred Successfully."
else
	echo "File transfer failed."
fi
