#!/usr/bin/env bash
#Config client server
Host school
    Host 52.91.184.60
    User ubuntu
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
